server:
    port: 8402
    servlet:
      context-path: /ui
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8401/oauth/token
      userAuthorizationUri: http://localhost:8401/oauth/authorize
    resource:
      userInfoUri: http://localhost:8401/user/me
spring:
  thymeleaf:
    cache: false
